version: '3.1'

services:

  mariadb:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - 3306:3306

  munity-backend:
#    image: munity-backend
    build:
      context: .
    ports:
      - 5001:80
    environment:
      - MUNITY_FRONTEND_IP=DOMAIN

