name: .NET Core Full Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100-preview1-014459
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
        working-directory: ./MUNityAngular/ClientApp
    - name: Install Angular-CLI
      run: npm install -g @angular/cli        
    - name: Try some stuff
      run: cd ./MUNityAngular/ClientApp && ls -a
    - name: Get files
      run: ls -a
    

