name: Test MUNityCore

on: [push]

jobs:
  testcore:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Start MongoDB
      run: sudo docker run --name mongo -d -p 27017:27017 mongo
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Run NUnit Tests
      run: dotnet test tests/MUNityTest

