name: BuildTestAndDeploy

on: [push]

jobs:
  testcore:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run Base Tests
      run: dotnet test tests/MUNityBaseTest --no-build --verbosity normal
    - name: Run Database Tests
      run: dotnet test tests/MUNityDatabaseTest --no-build --verbosity normal
    - name: Run Schema Test
      run: dotnet test tests/MUNitySchemaTests --no-build --verbosity normal
    - name: Run Service Tests
      run: dotnet test tests/MUNityServicesTest --no-build --verbosity normal
    - name: Move TestDatabase to main-project
      run: rm src/MUNity.BlazorServer/demo.* && cp tests/MUNityDatabaseTest/bin/Debug/net6.0/testmunbw.db src/MUNity.BlazorServer/demo.db && cp tests/MUNityDatabaseTest/bin/Debug/net6.0/testmunbw.db-wal src/MUNity.BlazorServer/demo.db-wal && cp tests/MUNityDatabaseTest/bin/Debug/net6.0/testmunbw.db-shm src/MUNity.BlazorServer/demo.db-shm
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        script: | 
          cd munity 
          git pull
          docker-compose up -d --build

