name: Test MUNityCore

on: [push]

jobs:
  testcore:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Run Base Tests
      run: dotnet test tests/MUNityBaseTest
    - name: Run Database Tests
      run: dotnet test tests/MUNityDatabaseTest
    - name: Run Schema Test
      run: dotnet test tests/MUNitySchemaTests
    - name: Run Service Tests
      run: dotnet test tests/MUNityServicesTest

