name: BuildTestAndDeploy

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  testcore:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run Base Tests
      run: dotnet test tests/MUNityBaseTest --no-build --verbosity normal
    - name: Run Database Tests
      run: dotnet test tests/MUNityDatabaseTest --no-build --verbosity normal
    - name: Run Schema Test
      run: dotnet test tests/MUNitySchemaTests --no-build --verbosity normal
    - name: Run Service Tests
      run: dotnet test tests/MUNityServicesTest --no-build --verbosity normal
    #- name: Move TestDatabase to main-project
    #  run: rm src/MUNity.BlazorServer/demo.* && cp tests/MUNityDatabaseTest/bin/Debug/net6.0/testmunbw.db src/MUNity.BlazorServer/demo.db && cp tests/MUNityDatabaseTest/bin/Debug/net6.0/testmunbw.db-wal src/MUNity.BlazorServer/demo.db-wal && cp tests/MUNityDatabaseTest/bin/Debug/net6.0/testmunbw.db-shm src/MUNity.BlazorServer/demo.db-shm
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}