name: Test Shared Code (MUNitySchema)

on: [push]

jobs:
  testshared:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Run NUnit Tests
      run: dotnet test tests/MunityNUnitTest
